### ISSUE TITLE
Why does the library throw "failed to load external entity" on credential error?

### ISSUE THREAD

**Issue by tekoyaki** [opendns/autotask-php#116]
> Warning (2): SoapClient::SoapClient(https://webservices6.autotask.net/ATServices/1.5/atws.wsdl) [soapclient.soapclient]: failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
> [APP/vendors/opendns/autotask-php/src/Client.php, line 133]
Warning (2): SoapClient::SoapClient() [soapclient.soapclient]: I/O warning : failed to load external entity "https://webservices6.autotask.net/ATServices/1.5/atws.wsdl" [APP/vendors/opendns/autotask-php/src/Client.php, line 133]

When I read that, I thought there's something wrong in routing or other network-related issues. Would it be possible to return a "credential error" message instead?

I see a few confused people reported the same, and they were all closed:

- https://github.com/opendns/autotask-php/issues/95
- https://github.com/opendns/autotask-php/issues/97

**Comment by reynolek** [comment]
Unfortunately because of the way the error is coming back, its not possible to return anything different here that will consistently be correct. There are other reasons why the soap client is unable to get the external wsdl (such as it just not even being there, or wrong url). The error that is being listed is the error that the php built in SoapClient is returning, not a special one from Autotask or even from this library.
