### ISSUE TITLE
How to add LIMIT, ORDER BY and GROUP BY in query

### ISSUE THREAD

**Issue by Bryannzx** [opendns/autotask-php#125]
Hi,

Is there a way to add limit, order by, group by and offset in query?

**Comment by SirPoot-** [comment]
Negative. These are not offered in this SOAP based API. The maxed returned is 500 items. You will have to do the rest after you've acquired your data.

**Comment by Bryannzx** [comment]
how about order by? is there away?

**Comment by JoshNW** [comment]
From The API Documentation 

> Use multiple queries to retrieve over 500 records
When constructing queries, be aware that Autotask will return only 500 records at once, sorted by id. If there are over 500
records that meet your criteria, you must create multiple queries where each query filters for id value > the maximum value
received in the previous query.
https://ww14.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_5.pdf
(page 10)

Autotask does not currently support sorting, filtering, or grouping. The best that can be done is to specify your start point by ID.

Example:
	$Id = new ATWS\AutotaskObjects\QueryField('id');
	$Id->addExpression('greaterthan', '###');

**Comment by SirPoot-** [comment]
@JoshNW is correct. Any time I need to obtain more than 500 record, I have to add a the 'greaterthan' expression with the last id of the entity I processed.

@Bryannzx we've provided the available answer and not response from you in a couple of months. Please close this issue.

**Comment by ravisoni** [comment]
Is that issue resolved yet , do we can get data using limit, order by and group by tags ?

**Comment by SirPoot-** [comment]
@ravisoni  you can get current usage by using the APIStats call.

Order by and group by are not available.

**Comment by ravisoni** [comment]
Thank you for your reply but please clear me it more as I need to fetch data from API in batch like 50 or 100 in single run so is there any Limit from and Limit to option to get data accordingly...
Reason I can not put Id condition in that case to fetch data from Id 1 to Id 50 and so on....  because in some API for eg during fetch contact based on marketing group then different group contact is there on that particular Id so Id can be mismatch and we can lost data during sync in batch....
Let me know if I am unable to clarify my issue and is there any solution we have to handle it would glad to use that ?

**Comment by SirPoot-** [comment]
@ravisoni can you please manage (hopefully close) your old/stale issues? #142 #129 Trying to keep the repo clean.

@ravisoni As mentioned in https://github.com/opendns/autotask-php/issues/125#issuecomment-442867482, Every Autotask query returns up to 500 records. The returned data is always ordered by ID in ascending order. On your condition, instead of using equals use greaterthan to get more than one record. Adding two conditions, Using the greaterthan and lessthan you can perform your limit for example, 1 - 50.  

If you want the next 500, get the ID of the last record and have that be the greaterthan value.

Most Autotask Entities have an ID, some do not and a little harder to “sync”.

I do not have access at the moment to the API documentation and cannot talk directly to contact groups. 

Let me if that clears things up.

**Comment by ravisoni** [comment]
Yes I saw in documentation that ( Autotask returns no more than 500 records per entity at once ) we can use Id using condition. But in specific case that concept not working like when syncing contact from particular marketing group
------
I am trying to explain by example and case we are facing hope that works and you can guide us in right direction if we have solution for it.

For eg. We have Marketing group A, B and C we have and 50 contact each under those group.
So when we sync based on particular marketing group we get data of different Id on which they contact exists. say Id 1 to 10 there is "C" marketing group contact exists then Id 10-20 there is "A" then 20-25 id there is group "B" then again 25-30 id there is "A" group contact.
So if you notice Id node from API is not continue for particular marketing group it can be either after 100 id and so on so it we fetch in batch of 50 record based on Id condition will not get exact data we needed or sometime will not get data as on that particular Id there may be 50 other marketing group contact exists.

**Comment by KenEDirective** [comment]
Hello,

I would like to know if there is any knowledge of these being added in the future?

Regards,

**Comment by SirPoot-** [comment]
@KenEDirective Nothing I am aware of. Rumors are they are going to build a REST API in the future. Maybe it will be in there? If you are interested in this, add it to the Autotask community as a feature request.

**Comment by SirPoot-** [comment]
@ravisoni you are right. You will need to call the contact record via ID if you want to get the record.
