### ISSUE TITLE
Restrict TicketNotes Query

### ISSUE THREAD

**Issue by JoshNW** [opendns/autotask-php#126]
I am currently using the Autotask API to synchronize ticket information with a third party Vendor who happens to also be using Autotask .

By utilizing the following steps we are able to create and updated shared client accounts and their respective tickets with out exposing any clients or tickets that are not shared between the two companies. 

Set up steps

Copy the System Administrator Security Group and rename
Set Access for all modules to "none" (All objects not specifically referenced below, remain set to "none", "no" or unchecked)
Modify Security Settings
In CRM->
In company Type-> set access to "Customers and Canceled" to "Mine" 
In Object Permissions-> 
Set Company->Add to "Yes" 
Set Contacts-> Add to "Yes"
Set Notes -> Add to "Yes"
In Service Desk->
Set Tickets->View to "Mine + Company"
Set Tickets-> Add to "Yes"
Set Tickets-> Edit to "Yes"
Set Ticket Notes-> Edit to "Mine"
In Other->In Miscellaneous-> Check the box for "Can login to Web Services API"
Create a new User and assign them the Modified Security Level created Above:
NOTE: You will receive a notification informing you that is will take one user license. This is as designed. An API user (free) cannot be used for this integration. 
Set your new user as a member of the Account team for all Accounts that you with to share via API Integration. 
--------

Once these steps are complete, you are able to utilize the Autotask API to query and update tickets and accounts that you have specified by adding the new User to the Account team.

The problem: When doing a TicketNote Search Via API, this new user will be able to access ALL ticket notes. The Ticket Notes search seems to bypass all security. 

This fundamental security gap makes this method of integration not viable. Is there a setting we have missed? Is this a bug? is there some alternative? 

 

One note is that the TicketNote View permissions are noticeably absent from the security level set up screen. I thought this was because the ticket note visibility was linked to ticket visibility, but it is not.

Please note, that This post has also been made to the AutoTask Community Page at this address
[https://success.autotask.net/t5/Professional-Services-Automation/Autotask-PSA-API-Restrict-TicketNotes/m-p/38589](url)

**Comment by SirPoot-** [comment]
Unfortunately, this is by design. No way I know of locking that down within Autotask. You could email support@autotask.com and include 'API' in the subject so it gets routed properly. Autotask has a dedicated API support team now, YAY! They will do NOT provide code, but rather how their API is designed / works. Hopefully they could shed some light.

Another option would be to create an your own API for your partner and scope / filter their calls based on your needs. A lot of work for something that should be baked into Autotask.

You could also use TaskFire and that has its own quirks (that you listed on https://success.autotask.net/t5/Professional-Services-Automation/Add-Taskfire-Fields-to-Autotask-Interface-Taskfire-Queue/m-p/39387)

**Comment by JoshNW** [comment]
@SirPoot-  Thank you for the reply! 

I was able to speak to a member Autotasks API team and they suggested the same. 

There is a request to add security to this interaction, but it is simply not in place at this time.  

I'm going to close out as there isn't much more that can be done.
