### ISSUE TITLE
Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host

### ISSUE THREAD

**Issue by JoshNW** [opendns/autotask-php#160]
I am probably missing something obvious here, but this one is driving me up a wall and any assistance would be greatly appreciated. 

We are doing bulk data updates via API. The script I am using pulls info from our billing system then checks to make sure Configuration Items are correctly configured. 

The script will run through about 300 rows then generate the following error and stop:

> Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in /var/www/html/vendor/opendns/autotask-php/src/Client.php:261** Stack trace: #0 /var/www/html/vendor/opendns/autotask-php/src/Client.php(261): SoapClient->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0) #1 [internal function]: ATWS\Client->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0) #2 /var/www/html/vendor/opendns/autotask-php/src/Client.php(266): SoapClient->__soapCall('update', Array) #3 /var/www/html/vendor/opendns/autotask-php/src/Client.php(168): ATWS\Client->_call('update', Array) #4 /var/www/html/vendor/opendns/autotask-php/Prod_CG2AT_Configuration_Items_Build.php(704): ATWS\Client->update(Object(ATWS\AutotaskObjects\InstalledProduct)) #5 {main} thrown in /var/www/html/vendor/opendns/autotask-php/src/Client.php on line 261

I know that line is a mess, but from I can gather, it looks like after successfully making about 750 calls to Autotask, application abruptly loses the ability to connect and generates that error. For reference line 704 in the script is an update call: "$result = $client->update($ConfigItem); "

From what I can tell, this occurs while connecting to the API not as a result of the information being passed.

**Comment by SirPoot-** [comment]
I've been experiencing some connectivity errors with Autotask recently; failed to fetch HTTP headers from time to time and they were down (UI and API) for a couple of minutes on my zone yesterday. Service availability my be the root cause. Especially, if it was working prior.

Once thing I wanted to mention was the use of the bulkUpdate method on the client. It will allow you to update 200 entities within a single request instead of 200 individual requests. You just need to split up the objects into small enough arrays. There is also bulkCreate and bulkDelete. With that said, the error handling for the bulk is a little pain. If there is an error in any one of the 200 entities, the whole bulk errors out and no changes are made. The response does tell you which object in the array caused the error so you can update and/or remove that individual object and try again. You can then handle the causer as needed.

**Comment by JoshNW** [comment]
We were able to confirm that this occurs when you cross the threshold.

Autotask support has informed us that there is no lockout period when a threshold is reached, testing confirmed that our API accounts lockout for 90 seconds upon reaching usage threshold, and then see the slow down implemented after that point. 

We were able to work with support to temporarily increase out threshold limits during data migration, which alleviated the problem. 

@SirPoot- we have avoided using 200 updates at a time because the error handling is too much to take on at the moment. I appreciate the response and am closing this thread.
