### ISSUE TITLE
Return only Installed Product UDF 

### ISSUE THREAD

**Issue by Capmouda** [opendns/autotask-php#24]
Hello All, I know i have been active on this :) and asking too many questions. Promise to show end result (If any).

I am trying to get Installed Products for a specific account. which is fine, except that the results brings returns all the UDF that is not even related to the product or the item. I noticed that Autotask Client Portal (for clients) is also having the same issue. 

Is this by design, is it locked by AT. 
Here is my query. how do i define that for each item, only return the related UDF.

```
        $id = $_REQUEST['id'];
        global $client;

        $query = new ATWS\AutotaskObjects\Query('InstalledProduct');

        $action = new ATWS\AutotaskObjects\QueryField('AccountID');
            $action->addExpression('equals', $id);

        $query->addField($action);
        $result = $client->query($query);

        $final = $result->queryResult->EntityResults->Entity;

        return $final;

```

Thank you.

**Comment by sureshkumar84** [comment]
Hi Capmouda, 

Even I can't configure autotask with my product, can you guide to configure with my product. I don't understand the below steps,

"Composer creates its own autoloader. Include vendor/autoload.php in your application config file and you will have full access to the autotask-php client."

**Comment by reynolek** [comment]
@Capmouda The way that autotask works (to my knowledge) is that every UDF is attached to every product unless you specifically set certain UDFs to be assigned to a product.

You can try to add a Configuration Item Type and see if that limits the number of UDFs pulled down.

@sureshkumar84 After using composer to install the client, there will be a vendor folder, `vendor/autoload.php` is a file that you then need to include anywhere you wish to use the client.

If you continue to have issues, please open a separate issue so that we can keep these comments focused on the problem that @Capmouda is having.

**Comment by Capmouda** [comment]
@reynolek Thanks - will try.

**Comment by SirPoot-** [comment]
@reynolek close request
