### ISSUE TITLE
How can i sent the data to auto task account

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [opendns/autotask-php#58]
I have to create an UDF  for each and every user and sent the UDF to auto task account using php after i need an ticket id for each and every user I am new one to auto task.
May I know how to do this?

**Comment by SirPoot-** [comment]
BUHARIMOHAMEDISMAIL -

It sounds like you have a lot going on. As of now, there is no access to any feature in the "ADMIN" module. i.E - resources.

Regarding the UDF, you can set it on the initial create or on a query/update. If you look back through the issues you will one examples. I know this because I've worked one out with @reynolek
