### ISSUE TITLE
Query without conditional

### ISSUE THREAD

**Issue by tekoyaki** [opendns/autotask-php#74]
Would it be possible to do a query without any conditionals? I keep getting ReturnCode 0 if I do this, and will have to pass on like `$field->addExpression('BeginsWith', '');` just to list everything in an entity.

Another default workaround:

```
    $field = new ATWS\AutotaskObjects\QueryField('id');
    $field->addExpression('NotEqual', 0);
    $query->addField($field);
```

**Comment by reynolek** [comment]
Most times you will want some kind of a conditional, because autotask will limit your query without really telling you.

I dont think ive ever tried to do it without a conditional, but its possible the code expects you to pass in one. This may be an oversight just from the base use case/assumptions made from original dev work on this client.

**Comment by tekoyaki** [comment]
For most entities I can just pass on Active = 1 or IsActive = 1. But there are some that don't have the active field, like Tax for example. So I have to pass on an arbitrary condition or id != 0.

**Comment by SirPoot-** [comment]
Every object you can query has an id field. Even if it is not in lists in the Objects php file.
